### PR TITLE
Enable Email + Username Login using Identifier.

### PR DESCRIPTION
**Pull request by sudodaksh**

### CODE REVIEW

**Comment by benawad** [comment]
Overall it looks good, and I like the idea. I'm happy to merge but before I do, I have a few questions for you.

1. This will require a change in the frontend to use identifier and email/username, would you like to submit a pr for that too?
2. Instead of using a regular expression, what do you think about checking whether the identifier matches an email or username in the database and not worry about identifying it ourselves? If you like the regular expression method better (which actually might create a faster db query), I think it would be better to use [validate.js](https://validatejs.org/#validators-email) to check whether it's an email to be consistent with our code here: https://github.com/benawad/slack-clone-server/blob/56_auto_deploys/src/models/user.js#L24

**Comment by sudodaksh** [comment]
I'm not sure if we need to use validate.js and I'll try to submit a pr for frontend.

**Comment by sudodaksh** [comment]
@benawad  ?

**Comment by benawad** [comment]
What's up

**Pull request closed without merging**
